version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build"
  build:
    commands:
      - echo "Entered the build"
      - mvn clean prepare-package war:explode
  post_build:
    commands:
      - echo "Entered the post-build"
      - mv targer/deploy ./
artifacts:
  files:
   - deploy/**/*